### PR TITLE
Fix messages to multiple channels

### PR DESCRIPTION
**Pull request by Xento**

### CODE REVIEW

**Comment by pa-pa** [comment]
Implemented by own code. Thank your for the hints.

**Comment by Xento** [comment]
If  two channels are peered it doesn't matter if one is inhibited or.
Your implementation sends the status back when one channel is inhibited.

**Comment by pa-pa** [comment]
Do you think this is a problem ? I want to make the code as fast as possible as well as minimal messages used. So if the channel is locked is it ignored for further processing. The test for inhibit is very fast, because it only check an internal channel value. 
If we only change the state of one channel then we can use the Ack to send the status back. By doing this we do not need a second status message.

**Comment by Xento** [comment]
I don't know.
I just wanted to notice that you behaviour ist different from the default one.
Does a peer need a status?
Maybe sender like HM-PB-4Dis-WM and HM-RC-Dis-H-x-EU need a status back.
But maybe they work in a completly different way.
I dont have a sender with a display so I can't test it.

**Pull request closed without merging**
