### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by trilu2000**
because of new HW and changes in STM32duino (new version)

### CODE REVIEW

**Comment by pa-pa** [comment]
I'm a little bit confused by the check results. Is this now working or not ?
I also do not understand, why mega128 examples are effected.

**Comment by trilu2000** [comment]
Me too, I have tested it locally and can not understand the errors.
It seems that something is missing at the automatic checks:
mega128 - fatal error: U8g2lib.h: No such file or directory
168p - fatal error: EnableInterrupt.h: No such file or directory

**Comment by jp112sdl** [comment]
War nur der eine Run (push des Commit) fehlerhaft. Danach lief er durch (beim PR)
Bildschirmfoto 2021-05-04 um 08 27 15

**Comment by pa-pa** [comment]
Dann können wir es also mergen ?

**Pull request merged**
