### PR TITLE
OffDelayBlink in dimmer implemented

### PR DESCRIPTION
**Pull request by trilu2000**
OffDelayBlink implemented. Blink duration and level of reduction are hardcoded, not sure if there are parameter in list3 exist?

### CODE REVIEW

**Comment by pa-pa** [comment]
There is the SHORT/LONG_OFFDELAY_BLINK register in List3. We should use the settings from there to decide, if the blink should active.

**Comment by pa-pa** [comment]
Oh - sorry - it is already used.

**Comment by trilu2000** [comment]
Does it work for you? Something missing?

**Comment by pa-pa** [comment]
Can you please check my proposal ? I have currently no hardware for test available.

**Comment by trilu2000** [comment]
which proposel you mean? i can confirm that my patch is working :-)
tested in the dim_pwm sketch and in the dual led sketch, it's working in both as expected and looks pretty much similar as in the HM Dimmer.

**Pull request merged**
