### PR TITLE
Fixed repeating longpress message for switch

### PR DESCRIPTION
**Pull request by Xento**

### CODE REVIEW

**Comment by pa-pa** [comment]
I changed some code to fix the repeating long press. Can you please check if the new code works as expected.

**Comment by Xento** [comment]
The bug is still there.
When you long press and it is set to toggle in the easy mode than it turns on and off while you hold the button.

**Comment by pa-pa** [comment]
Do you think that is really a problem ?
The switch channel class will now initialize LONG_MULTIEXECUTE to off for single peers.

**Comment by Xento** [comment]
I will try it.
I don't know if the ccu sets multiexec to true when using the simple mode "On/Off".
What about the delay behaviour?
Is it implemented?
You could use this function as door opener.
As long as you press the button, the door is opened, when you release it it will turn off the opener.

**Comment by pa-pa** [comment]
Delay timer are implemented. So if you set action to ON and onTime to 1sec it should stay on as long as the long events appear. It will switch off 1 sec after the last long event.

**Comment by pa-pa** [comment]
closed

**Pull request closed without merging**
