### PR TITLE
make flushFIFO function accessible to sketches

### PR DESCRIPTION
**Pull request by Xento**
In case of receiving problems it is useful to be able to call the flushFIFO function to get the CC1101 working again.
This could be implemented in the sketch with an alarm.

### CODE REVIEW

**Comment by pa-pa** [comment]
You can simply use device.radio().flushrx();

**Comment by Xento** [comment]
Ah thank you for this information.

**Comment by Xento** [comment]
I tried to implement this

I added a class in the sketch and set up an alarm:
`class FlushRXAlarm : public Alarm {
public:
  FlushRXAlarm () : Alarm(0) { async(false); }
  virtual void trigger (AlarmClock& clock) {
   device.radio().flushrx();

   tick = seconds2ticks(60);
   clock.add(*this);
  }
};`
I get an error when compiling:
'device' was not declared in this scope

**Comment by pa-pa** [comment]
The radio is a member of the HAL. So define your class after defining the global HAL instance. Then use 

hal.radio.flushrx();

Other option would to set the reference to the device into the Alarm

**Comment by Xento** [comment]
I got it but some change is nessesary.
The function flushrx has to be moved to the public section or define a public function that calls the protected one.

**Pull request merged**
