### PR TITLE
Fixed two drive bugs

### PR DESCRIPTION
**Pull request by Xento**
With this changes you can trigger to drive up or down even when the actor things the endposition is already reached. This is nessesary to correct the position of the blind when it didn't reached the correct endposition.
Additionally when you drive to an endposition 2 seconds are added to the total drivetime to ensure you really reach the endposition for example when your blind drives slower oder faster depending on the wheatherconditions or when you didn't calculated the correct drivetimes for you blind.

### CODE REVIEW

**Comment by pa-pa** [comment]
Have you tested with long press? I think long press will no longer work when you remove the minimal drive time of 2 seconds in calcDriveTime.

**Comment by Xento** [comment]
No, I will test it today.
At the moment I don't know which content the long press has but in my opinion it can't set the destination level because the destination is reached when ever you release the button or is the destination set to max and after the release there will be a stop message?
I will test it when I'm at home again.

**Comment by Xento** [comment]
I think there is someting wrong with the longpress.

Here the output:
-> 0B 7D 84 40 5667E7 5932AF 46 66  - 41043
Switch from 08 to 03
STOP
-> 0B 7E 84 40 5667E7 5932AF 46 66  - 41310
Switch from 03 to 01
Switch from 01 to 02
All Buttons off
-> 0B 7F 84 40 5667E7 5932AF 46 66  - 41576
Switch from 02 to 08
UP
<- 0E 0F A2 10 5932AF 473071 06 01 42 50 76  - 41701
-> 0B 81 84 40 5667E7 5932AF 46 66  - 42110
waitAck: 00
<- 0E 0F A2 10 5932AF 473071 06 01 42 50 76  - 42344
-> 0B 82 84 40 5667E7 5932AF 46 66  - 42379
-> 0A 0F 80 02 473071 5932AF 00  - 42475
waitAck: 01
All Buttons off
Switch from 08 to 03
STOP
<- 0E 10 A2 10 5932AF 473071 06 01 42 00 58  - 42510
-> 0B 83 84 40 5667E7 5932AF 46 66  - 42645
-> 0B 84 84 40 5667E7 5932AF 46 66  - 42913
waitAck: 00
<- 0E 10 A2 10 5932AF 473071 06 01 42 00 58  - 43157
-> 0A 10 80 02 473071 5932AF 00  - 43284
waitAck: 01
All Buttons off
-> 0B 86 84 40 5667E7 5932AF 46 66  - 43323
Switch from 03 to 01
Switch from 01 to 02
-> 0B 87 84 40 5667E7 5932AF 46 66  - 43589
Switch from 02 to 08
UP
<- 0E 11 A2 10 5932AF 473071 06 01 42 50 76  - 43712
-> 0A 11 80 02 473071 5932AF 00  - 43837
waitAck: 01
Switch from 08 to 03
STOP
-> 0B 88 84 40 5667E7 5932AF 46 66  - 43855
Switch from 03 to 01
Switch from 01 to 02
-> 0B 89 A0 40 5667E7 5932AF 46 66  - 44122
Switch from 02 to 08
UP
<- 0E 89 80 02 5932AF 5667E7 01 01 42 50 73  - 44240
Switch from 08 to 03
STOP
ignore 0B 8A A2 40 5667E7 473071 46 66  - 44412
ignore 11 8A A0 02 473071 5667E7 04 A1 FF 25 F1 00 23 06  - 44544
All Buttons off

It seems that there is something wrong with the longpress.
It cycles to all states ...

**Comment by pa-pa** [comment]
I have add an extra option when calculating the drive time. I think this should work. Not really tested yet.

**Comment by Xento** [comment]
I had an bug in my sketch with the peerings for the ccu, so long press wasn't working.
When you long press, the function to calculate the drivetime is never called.
With my version long press works.

**Pull request closed without merging**
