### PR TITLE
Led: do blink updates with enabled interrupts

### PR DESCRIPTION
**Pull request by maniac103**
This is needed when using a PCF8574 to drive LEDs.

### CODE REVIEW

**Comment by pa-pa** [comment]
If I remember right, the reason for the ATOMIC block was the next() method. We need to ensure that the manipulation of the tick variable is atomic with adding the alarm to the clock. I would suggest the following changes:
next() do not change the led state - it only returns the state to set:

`bool next (AlarmClock& clock) {
    tick = decis2ticks(current.pattern[step++]);
    clock.add(*this);
    return ((step & 0x01) == 0x01);
  }`

Then the trigger can be implemented like this

`virtual void trigger (AlarmClock& clock) {
    bool swtichon=false; // default switch off
    ATOMIC_BLOCK( ATOMIC_RESTORESTATE ) {
      if( step < current.length ) {
        switchon = next(clock);
      }
      else {
        step = 0;
        if( current.duration == 0 || ++repeat < current.duration ) {
          switchon = next(clock);
        }
        else {
          // off is default
          copyPattern(nothing,single);
        }
      }
    }
    if( switchon == true ) ledOn();
    else ledOff();
  } `

All other next() calls needs an additional ledOn() - because they always starts a pattern.
I have no hardware to check, so please try and feedback.

**Comment by maniac103** [comment]
> I have no hardware to check, so please try and feedback.

I'll do, and your suggestion sounds good to me, but we'll still need the `NONATOMIC_BLOCK` since the `trigger` methods are already run in an `ATOMIC_BLOCK` (strictly speaking the atomic block in `Led::trigger` is redundant, but I think it's still helpful to be clear about the intent).

**Comment by pa-pa** [comment]
trigger is only in an ATOMICBLOCK if it is async - means it runs directly during the timer interrupt. In the other case it it sunning during the main loop synchron to the application code.

**Comment by maniac103** [comment]
> trigger is only in an ATOMICBLOCK if it is async 

Yep, noticed that after my comment (while pondering #269). I changed the code to use your suggestion, which - together with running the LED in synchronous mode - works fine.

**Pull request merged**
