### PR TITLE
added check routine for correct measurement on DHT sensor

### PR DESCRIPTION
**Pull request by jp112sdl**
- the measurement of DHT22 sensor sometimes returns zero values (reported by a user and verified by me)
- to reduce failures, I added the `isnan` check, as seen in an example sketch of the DHT library.

bildschirmfoto 2018-03-28 um 20 04 54

### CODE REVIEW

**Comment by pa-pa** [comment]
I do not like this solution, because of the loop inside the measure method, it is no longer possible to use a  maximal measure time for that sensor in the application code. If you have some hard real-time constraints, like hit the next send slot, you need a working maximal running time for the measurement code.
I would suggest to let the measure method return a bool value, which shows if the measurement was successful. So the calling code can react on this. Last values will be returned if he measurement fails.

**Comment by jp112sdl** [comment]
What about this suggestion: we implement a counter.
If measurement fails, it will be retried max. 10 times, after that it will return 0 / 0 values.

The DHT(22) sensor itself is not a very practical one.
I also had trouble with this kind on an esp8266 where I had to wait 4 seconds between powering up and first measurement.
But it is a cheap sensor, not very precise. 
And I don't think that it is usable for e.g. a thermostat device peering.

**Comment by pa-pa** [comment]
I think we can have both. The current measure() can be changed to return the success of the measurement. A second measure(uint8_t repeat) will call the "simple" measure and tries multiple times if needed. It can also reset the values to 0 if it is not possible to get any data.

**Comment by pa-pa** [comment]
What about this implementation - a little bit more compact. 

`template <int DATAPIN,int TYPE=DHT11,uint8_t MAXMEASURE=1>
class Dht : public Temperature, public Humidity {
  DHT _dht;
public:
  Dht () : _dht(DATAPIN,TYPE) {}
  void init () {
    _dht.begin();
    _present = true;
  }
  bool measure (__attribute__((unused)) bool async=false) {
    bool success = false;
    if( present() == true ) {
      uint8_t measure=MAXMEASURE;
      while( success == false && measure > 0 ) {
        --measure;
        float t = _dht.readTemperature(false,true);
        float h = _dht.readHumidity();
        if( (isnan(t) == false && isnan(h) == false ) {
          _temperature = t * 10;
          _humidity = h;
          success = true;
        }
        else if( measure > 0 ) {
          _delay_ms(500);
        }
      }
    }
    return success;
  }
};
`

**Comment by pa-pa** [comment]
Have you run the code? I currently have no DHT test hardware. So I'm not able to test the code. I don't like committing untested code.

**Comment by jp112sdl** [comment]
There was a little mistake in your code
`if( (isnan(t) == false && isnan(h) == false ) ` had one `(` too much. 

But now the code is running correct on succesful measurements and retries for MAXMEASURES. 👍 

I have pushed your code in my PR (e709347), so that you may now merge it.

**Comment by pa-pa** [comment]
Because of the different code formatting, I used my code. Thank you for your support and testing.

**Pull request closed without merging**
